name: Update Galaxia SVG

on:
  schedule:
    - cron: "17 5 * * *" # daily 05:17 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip requests

      - name: Generate Galaxia SVG
        env:
          GITHUB_LOGIN: AidanHT
          GITHUB_TOKEN: ${{ secrets.GALAXIA_TOKEN }}
        run: |
          python scripts/generate_galaxia.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add docs/assets/galaxia.svg
            git commit -m "chore(galaxia): auto-update commit arcade SVG"
            git push
          else
            echo "No changes"
          fi
